version: '3.3'
services:
  headscale:
    container_name: 'headscale'
    image: 'headscale/headscale:0.19'
    volumes:
        - '.docker/headscale/config:/etc/headscale/'
    ports:
        - '127.0.0.1:8080:8080'
        - '127.0.0.1:9090:9090'
    command: headscale serve
  vault:
    container_name: 'vault-server'
    image: local.dev/vault-with-headscale-plugin:latest
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.vault
    command: vault server -dev -dev-root-token-id=root -dev-plugin-dir=/vault/plugin
    volumes:
      - '.docker/vault/config:/etc/vault/'
    environment:
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_LOG_LEVEL=trace
    ports:
      - '127.0.0.1:8200:8200'
    cap_add:
      - IPC_LOCK
    