---
server_url: http://headscale:8080


listen_addr: 0.0.0.0:8080

metrics_listen_addr: 0.0.0.0:9090

grpc_listen_addr: 127.0.0.1:50443

grpc_allow_insecure: false

private_key_path: /tmp/private.key

noise:
  private_key_path: /tmp/noise_private.key
ip_prefixes:
  - 100.80.0.0/10

derp:
  server:
    enabled: false

    region_id: 999
    region_code: "headscale"
    region_name: "Headscale Embedded DERP"
    stun_listen_addr: "0.0.0.0:3478"
  urls:
    - https://controlplane.tailscale.com/derpmap/default
  paths: []
  auto_update_enabled: true
  update_frequency: 24h

disable_check_updates: false

ephemeral_node_inactivity_timeout: 30m

node_update_check_interval: 10s

db_type: sqlite3

db_path: /tmp/db.sqlite

acme_url: https://acme-v02.api.letsencrypt.org/directory

acme_email: ""

tls_letsencrypt_hostname: ""

tls_letsencrypt_cache_dir: ./cache

tls_letsencrypt_challenge_type: HTTP-01

tls_letsencrypt_listen: ":http"

tls_cert_path: ""
tls_key_path: ""

log:
  format: text
  level: info

acl_policy_path: ""

dns_config:
  override_local_dns: true

  nameservers:
    - 1.1.1.1
  domains: []
  magic_dns: true
  base_domain: example.com

unix_socket: ./headscale.sock
unix_socket_permission: "0770"
logtail:
  enabled: false

randomize_client_port: false