FROM library/vault:1.8.12
RUN mkdir -p /vault/plugin
COPY bin/vault-plugin-headscale /vault/plugin/
RUN chown -R vault:vault /vault/plugin
RUN setcap cap_ipc_lock=+ep  /vault/plugin/vault-plugin-headscale